=== AdapterKernel/X-Road/xtee6/common-util/src/main/resources/globalconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sdsb.net/xsd/sdsb.xsd"
    targetNamespace="http://sdsb.net/xsd/sdsb.xsd" xmlns:id="http://sdsb.net/xsd/identifiers">
    <import namespace="http://sdsb.net/xsd/identifiers" schemaLocation="identifiers.xsd" id="id"/>
    <complexType name="GlobalConfType">
        <sequence>
            <element name="instanceIdentifier" type="string">
                <annotation>
                    <documentation>Name that identifies this instance of the SDSB system.</documentation>
                </annotation>
            </element>
            <element name="member" type="tns:MemberType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Data of the registered organizations.
                    </documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="memberClass"
                type="tns:MemberClassType"/>
            <element maxOccurs="unbounded" minOccurs="0" name="securityCategory"
                type="tns:SecurityCategoryType"/>
            <element maxOccurs="unbounded" minOccurs="0" name="securityServer"
                type="tns:SecurityServerType">
                <annotation>
                    <documentation>Information about security servers.</documentation>
                </annotation>
            </element>
            <element name="globalGroup" type="tns:GlobalGroupType" maxOccurs="unbounded"
                minOccurs="0">
                <annotation>
                    <documentation>
                        Organization groups defined by the central
                        agency.
                    </documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="centralService"
                type="tns:CentralServiceType"/>
            <element name="pki" type="tns:PkiType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        PKI element corresponds to a certification
                        hierarchy ending with a common trust anchor.
                    </documentation>
                </annotation>
            </element>
            <element name="approvedTsp" type="tns:ApprovedTspType" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Information about time stamp service providers.
                    </documentation>
                </annotation>
            </element>
            <element name="globalSettings" type="tns:GlobalSettingsType">
                <annotation>
                    <documentation>
                        Miscellaneous information for various system modules
                    </documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="MemberType">
        <annotation>
            <documentation>Represents information about a member of the SDSB.</documentation>
        </annotation>
        <sequence>
            <element name="memberClass" type="tns:MemberClassCodeType">
                <annotation>
                    <documentation>Refers to the class of the member</documentation>
                </annotation>
            </element>
            <element name="memberCode" type="string">
                <annotation>
                    <documentation/>
                </annotation>
            </element>
            <element name="name" type="string">
                <annotation>
                    <documentation>Full, official name of the member, used in user interfaces.
                    </documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="subsystem" type="tns:SubsystemType"/>
        </sequence>
        <attribute name="id" type="ID"/>
    </complexType>

    <complexType name="SecurityServerType">
        <annotation>
            <documentation>Represents information about a security server.</documentation>
        </annotation>
        <sequence>
            <element name="owner" type="IDREF">
                <annotation>
                    <documentation>Auto-generated xml id for referencing inside xml. Connects sdsb member and security server(s) this member owns.</documentation>
                </annotation>
            </element>
            <element name="serverCode" type="string">
                <annotation>
                    <documentation/>
                </annotation>
            </element>
            <element minOccurs="0" name="address" type="string">
                <annotation>
                    <documentation>Address of this security server.</documentation>
                </annotation>
            </element>
            <element name="authCertHash" type="base64Binary" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Hash of the authentication certificate belonging to this security server.</documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="client" type="IDREF">
                <annotation>
                    <documentation>Reference to a client of this security server. Client can be either SDSB member or a subsystem.</documentation>
                </annotation>
            </element>
            <element maxOccurs="unbounded" minOccurs="0" name="securityCategory"
                type="tns:SecurityCategoryCodeType">
                <annotation>
                    <documentation>Code of the security category given to this security server.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <complexType name="PkiType">
        <sequence>
            <element name="name" type="string">
                <annotation>
                    <documentation>
                        Name of the PKI, just for displaying to users.
                    </documentation>
                </annotation>
            </element>
            <element name="authenticationOnly" type="boolean" minOccurs="0">
                <annotation>
                    <documentation>
                        If present and true, indicates that this PKI can
                        only be used for SSL authentication and not for
                        creating and verifying digital signatures.
                    </documentation>
                </annotation>
            </element>
            <element name="topCA" type="tns:CaInfoType">
                <annotation>
                    <documentation>
                        Topmost (usually self-signed) CA that is used as
                        trust anchor.
                    </documentation>
                </annotation>
            </element>
            <element name="intermediateCA" type="tns:CaInfoType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Intermediate CA. This information can be used
                        for certificate path building and finding OCSP
                        responders.
                    </documentation>
                </annotation>
            </element>
            <element name="nameExtractor" type="tns:NameExtractorType" minOccurs="0">
                <annotation>
                    <documentation>Name of the (fully qualified) static method that extracts unique identifier from the certificate.
The method takes as argument java.security.cert.X509Certificate object and returns String that contains the identifier.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="GlobalGroupType">
        <sequence>
            <element name="groupCode" type="string">
                <annotation>
                    <documentation>Code that uniquely identifies this group in a given SDSB instance.</documentation>
                </annotation>
            </element>
            <element name="description" type="string">
                <annotation>
                    <documentation>Human-readable name of the group.</documentation>
                </annotation>
            </element>
            <element name="member" type="id:SdsbClientIdentifierType" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>Identifier of subject belonging to group.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="OcspInfoType">
        <annotation>
            <documentation>Information about a single OCSP provider.</documentation>
        </annotation>
        <sequence>
            <element name="url" type="string">
                <annotation>
                    <documentation>URL of the server.</documentation>
                </annotation>
            </element>
            <element name="cert" type="base64Binary" minOccurs="0">
                <annotation>
                    <documentation>Certificate that the server uses to sign OCSP responses.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <element name="conf" type="tns:GlobalConfType">
        <annotation>
            <documentation>Topmost element for the global configuration.</documentation>
        </annotation>
    </element>

    <complexType name="ApprovedTspType">
        <sequence>
            <element name="name" type="string">
                <annotation>
                    <documentation>Name of the TSP, for display.</documentation>
                </annotation>
            </element>
            <element name="url" type="string">
                <annotation>
                    <documentation>URL of the TSP</documentation>
                </annotation>
            </element>
            <element name="cert" type="base64Binary">
                <annotation>
                    <documentation>Cert that the TSP uses to sign responses.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="CaInfoType">
        <annotation>
            <documentation>
                This type encapsulates information about a single CA
                certificate.
            </documentation>
        </annotation>
        <sequence>
            <element name="cert" type="base64Binary">
                <annotation>
                    <documentation>
                        The certificate value.
                    </documentation>
                </annotation>
            </element>
            <element name="ocsp" type="tns:OcspInfoType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>List of OCSP responders that provide status of certificates issued by this CA.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <complexType name="SubsystemType">
        <sequence>
            <element name="subsystemCode" type="string"/>
        </sequence>
        <attribute name="id" type="ID"/>
    </complexType>
    <complexType name="MemberClassType">
        <sequence>
            <element name="code" type="tns:MemberClassCodeType">
                <annotation>
                    <documentation>Code that uniquely identifies member class in this SDSB instance.</documentation>
                </annotation>
            </element>
            <element name="description" type="string"/>
        </sequence>
    </complexType>
    <complexType name="NameExtractorType">
        <sequence>
            <element name="memberClass" type="string">
                <annotation>
                    <documentation>Code of the member class of the extracted member code.</documentation>
                </annotation>
            </element>
            <element name="methodName" type="string">
                <annotation>
                    <documentation>Name of the public static method (formatted as ClassName.methodName) that takes a certificate as input and returns member code as output.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <complexType name="CentralServiceType">
        <sequence>
            <element name="serviceCode" type="string">
                <annotation>
                    <documentation>Code that uniquely identifies central service in this SDSB instance.</documentation>
                </annotation>
            </element>
            <element minOccurs="0" name="implementingService" type="id:SdsbServiceIdentifierType">
                <annotation>
                    <documentation>Real service that implements the central service</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    <complexType name="SecurityCategoryType">
        <sequence>
            <element name="code" type="tns:SecurityCategoryCodeType"/>
            <element name="description" type="string"/>
        </sequence>
    </complexType>
    <simpleType name="MemberClassCodeType">
        <annotation>
            <documentation>Specifies the structure of member class code</documentation>
        </annotation>
        <restriction base="string"/>
    </simpleType>
    <simpleType name="SecurityCategoryCodeType">
        <annotation>
            <documentation>Specifies the structure of security category code</documentation>
        </annotation>
        <restriction base="string"/>
    </simpleType>
    <complexType name="GlobalSettingsType">
        <sequence>
            <element name="managementRequestServiceAddress" type="string">
                <annotation>
                    <documentation>Address of the management request service.</documentation>
                </annotation>
            </element>
            <element name="managementRequestServiceId" type="id:SdsbClientIdentifierType">
                <annotation>
                    <documentation>Identifier of the management request service.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
</schema>

=== AdapterKernel/X-Road/xtee6/asicverifier/src/test/resources/globalconf.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:conf xmlns:id="http://x-road.eu/xsd/identifiers" xmlns:tns="http://x-road.eu/xsd/xroad.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://x-road.eu/xsd/xroad.xsd ../../../../common-util/src/main/resources/globalconf.xsd ">
    <instanceIdentifier>EE</instanceIdentifier>

    <member id="producerId">
        <memberClass>BUSINESS</memberClass>
        <memberCode>producer</memberCode>
        <name>Experimental producer</name>
    </member>
    
    <member id="consumerId">
        <memberClass>BUSINESS</memberClass>
        <memberCode>consumer</memberCode>
        <name>Experimental consumer</name>
    </member>

    <!-- <group> <shortName>shortName</shortName> <fullName>fullName</fullName> 
        <org>org</org> </group> <tsp> <name>name</name> <url>url</url> <cert>TODO 
        - WHICH CERT?</cert> </tsp> -->


    <pki>
        <name>pki1</name>
        <topCA>
            <!-- Extracted from: proxy/src/test/certs/admin-ca1.pem -->
            <cert>MIIDUzCCAjugAwIBAgIIU1eWoysptjUwDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwNjE0MTAwNDI5WhcNMjIwNjEyMTAwNDI5WjA3MREwDwYDVQQDDAhBZG1p
                bkNBMTEVMBMGA1UECgwMRUpCQ0EgU2FtcGxlMQswCQYDVQQGEwJTRTCCASIwDQYJ
                KoZIhvcNAQEBBQADggEPADCCAQoCggEBAILYKYehC6hsbPQnqBPWoatI8I7qZGow
                3otWO9pW8lMvjgNiE8Cl8oFQS+C3CaqSvHU+iXUVkIlHuAr6k30G/mm6JqU0zA2o
                2apt5HJFzkg/0/LvLbSB1S5e0VTRDhMncgJakEUJvHFL0aKtq1RigP9C7Zt5BdDy
                RBuJiutvaFjSeJ2sCQrHDcrJ1uAtdidv3z3Zih9O8CnalNZFltFf7M8pm+O+HIbu
                miA19kShJwvpcdC9fVPuwsF1Qbeo4SeKuDPU1KHq7ZP9Heh7P6eywxghkYC4yewj
                Bu8COi1FJMGHt9OdD+rNa/GTZ7ULPFiCH8wwCTn+YUtFe5pFLkvCG7sCAwEAAaNj
                MGEwHQYDVR0OBBYEFHctiS4Dtv340mU5MTUi0EYa6NIJMA8GA1UdEwEB/wQFMAMB
                Af8wHwYDVR0jBBgwFoAUdy2JLgO2/fjSZTkxNSLQRhro0gkwDgYDVR0PAQH/BAQD
                AgGGMA0GCSqGSIb3DQEBBQUAA4IBAQAnEhhOwvk2Goy+wRwZgQLkmv9QIzBwP+Bw
                d45DQOJyPjVTukNoc5w1y1in7yR9T8Cv5Ba1ctAqclztwjhAYAhWcG/CSZ4RvX8z
                ysbnthW6qhZGGz5KJATZhFYrIaNGqC9i0FfTe3PF3HaowqndnBFtwjV65mszTaTN
                p94LKhLk1ARc/BidplsM1cBSoA9VWvTANI8alKuJxh1QG9TbEJul1BTzA/wItMVD
                tganTDrQxmkP1NW7d+MsIB5AQHABaXWgjygcqoMlLjyH/0QOP13iyvMXQU4jtSla
                TmGm9CaC/xRQ10YD7AHHvq1P2cvfbQaV3I5xUYF7aqwM93ZjmptI
            </cert>
            <ocsp>
                <!-- Local OCSP responder simulator used currently -->
                <url>
	http://127.0.0.1:8082/ocsp</url>
                <!-- Extracted from: proxy/src/test/certs/ocspsigner.p12 -->
                <cert>MIIDizCCAnOgAwIBAgIIOmOWEyqjUj0wDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                    AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                    HhcNMTIwOTA2MTEzODMwWhcNMTQwOTA2MTEzODMwWjAWMRQwEgYDVQQDDAtPY3Nw
                    IFNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANZTdnxNq1QM
                    ncmiInNUSpm02V72GNrMrvq2Q4Zz3Zr8zDKMdAiwdrjx9X+Zi5oTjiSUXRuHY5ZN
                    9oeLO1cv9NV6OGk3MlrAzxquBfQUgnZMNLkPZW5SuLqlZpWf0vF7EvAVX20hxgMq
                    7M26Fxt/B9W81/G/REnuHKJ+nxCAZi5Kd1hdGVTEIwkicqROiEfQUcycs0T5aZI7
                    F5qFiZyo3AeRbWYyhEfe326cPaRaswo2WwcBjFYWibTCnNQuLgDL6qroL1T8soI6
                    LzBaNao6Lm4YY1OwTPz/UEiJ3KIXoAjfxMlOUnznmeWYNPcJb5Z8fdtWpaZqjV3W
                    IMAZocNThb8CAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGG
                    PGh0dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dl
                    Yi9zdGF0dXMvb2NzcDAdBgNVHQ4EFgQUI1mSgzcFjcBFmmjYwlc9Qm7yF/kwDAYD
                    VR0TAQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNV
                    HQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBACRO2KTCVKQxYMlsMDkjT5Qj
                    zqW0wHNCsxieYv0qfDM1Z5ceW0c0KjJcKXESj7GXT7oNejwI4gZNgxIzemJ3xABH
                    dftk2WxLQBYJMKQ30EuisFKueqpxaLVkPAbt+XLxSrxaYePB9LTJ+rw3FtbiIbag
                    3AH22TFUUUnaTGVF+OiHtthE1u7bnwsTqWXX4PI9I3KnSaIEE55mveNq2jHVWu4r
                    Myy2flOZMonYh3dw1gmSp2yWo1YDpN3olM0Li6Lnfvg1TZd71xZ6ZkKf+MoAs+pW
                    2HaLh8hiYRXpgw3WVSBg6CPTLoU5xFb57BNL3qccVetmbpZgznHMYEBN4b4pyHk=
                </cert>
            </ocsp>
            <ocsp>
                <url>http://nihhuijaa.example.net/ocsp</url>
                <cert>MIIDizCCAnOgAwIBAgIIOmOWEyqjUj0wDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                    AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                    HhcNMTIwOTA2MTEzODMwWhcNMTQwOTA2MTEzODMwWjAWMRQwEgYDVQQDDAtPY3Nw
                    IFNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANZTdnxNq1QM
                    ncmiInNUSpm02V72GNrMrvq2Q4Zz3Zr8zDKMdAiwdrjx9X+Zi5oTjiSUXRuHY5ZN
                    9oeLO1cv9NV6OGk3MlrAzxquBfQUgnZMNLkPZW5SuLqlZpWf0vF7EvAVX20hxgMq
                    7M26Fxt/B9W81/G/REnuHKJ+nxCAZi5Kd1hdGVTEIwkicqROiEfQUcycs0T5aZI7
                    F5qFiZyo3AeRbWYyhEfe326cPaRaswo2WwcBjFYWibTCnNQuLgDL6qroL1T8soI6
                    LzBaNao6Lm4YY1OwTPz/UEiJ3KIXoAjfxMlOUnznmeWYNPcJb5Z8fdtWpaZqjV3W
                    IMAZocNThb8CAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGG
                    PGh0dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dl
                    Yi9zdGF0dXMvb2NzcDAdBgNVHQ4EFgQUI1mSgzcFjcBFmmjYwlc9Qm7yF/kwDAYD
                    VR0TAQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNV
                    HQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBACRO2KTCVKQxYMlsMDkjT5Qj
                    zqW0wHNCsxieYv0qfDM1Z5ceW0c0KjJcKXESj7GXT7oNejwI4gZNgxIzemJ3xABH
                    dftk2WxLQBYJMKQ30EuisFKueqpxaLVkPAbt+XLxSrxaYePB9LTJ+rw3FtbiIbag
                    3AH22TFUUUnaTGVF+OiHtthE1u7bnwsTqWXX4PI9I3KnSaIEE55mveNq2jHVWu4r
                    Myy2flOZMonYh3dw1gmSp2yWo1YDpN3olM0Li6Lnfvg1TZd71xZ6ZkKf+MoAs+pW
                    2HaLh8hiYRXpgw3WVSBg6CPTLoU5xFb57BNL3qccVetmbpZgznHMYEBN4b4pyHk=
                </cert>
            </ocsp>
        </topCA>
        <nameExtractor>
            <memberClass>BUSINESS</memberClass>
            <methodName>ee.ria.xroad.common.cert.CertHelper.getSubjectCommonName</methodName>
        </nameExtractor>
    </pki>
    <pki>
        <name>pki2</name>
        <authenticationOnly>true</authenticationOnly>
        <topCA>
            <!-- Extracted from: proxy/src/test/certs/admin-ca1.pem -->
            <cert>MIIDUzCCAjugAwIBAgIIU1eWoysptjUwDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                HhcNMTIwNjE0MTAwNDI5WhcNMjIwNjEyMTAwNDI5WjA3MREwDwYDVQQDDAhBZG1p
                bkNBMTEVMBMGA1UECgwMRUpCQ0EgU2FtcGxlMQswCQYDVQQGEwJTRTCCASIwDQYJ
                KoZIhvcNAQEBBQADggEPADCCAQoCggEBAILYKYehC6hsbPQnqBPWoatI8I7qZGow
                3otWO9pW8lMvjgNiE8Cl8oFQS+C3CaqSvHU+iXUVkIlHuAr6k30G/mm6JqU0zA2o
                2apt5HJFzkg/0/LvLbSB1S5e0VTRDhMncgJakEUJvHFL0aKtq1RigP9C7Zt5BdDy
                RBuJiutvaFjSeJ2sCQrHDcrJ1uAtdidv3z3Zih9O8CnalNZFltFf7M8pm+O+HIbu
                miA19kShJwvpcdC9fVPuwsF1Qbeo4SeKuDPU1KHq7ZP9Heh7P6eywxghkYC4yewj
                Bu8COi1FJMGHt9OdD+rNa/GTZ7ULPFiCH8wwCTn+YUtFe5pFLkvCG7sCAwEAAaNj
                MGEwHQYDVR0OBBYEFHctiS4Dtv340mU5MTUi0EYa6NIJMA8GA1UdEwEB/wQFMAMB
                Af8wHwYDVR0jBBgwFoAUdy2JLgO2/fjSZTkxNSLQRhro0gkwDgYDVR0PAQH/BAQD
                AgGGMA0GCSqGSIb3DQEBBQUAA4IBAQAnEhhOwvk2Goy+wRwZgQLkmv9QIzBwP+Bw
                d45DQOJyPjVTukNoc5w1y1in7yR9T8Cv5Ba1ctAqclztwjhAYAhWcG/CSZ4RvX8z
                ysbnthW6qhZGGz5KJATZhFYrIaNGqC9i0FfTe3PF3HaowqndnBFtwjV65mszTaTN
                p94LKhLk1ARc/BidplsM1cBSoA9VWvTANI8alKuJxh1QG9TbEJul1BTzA/wItMVD
                tganTDrQxmkP1NW7d+MsIB5AQHABaXWgjygcqoMlLjyH/0QOP13iyvMXQU4jtSla
                TmGm9CaC/xRQ10YD7AHHvq1P2cvfbQaV3I5xUYF7aqwM93ZjmptI
            </cert>
            <ocsp>
                <!-- Local OCSP responder simulator used currently -->
                <url>
	http://127.0.0.1:8082/ocsp</url>
                <!-- Extracted from: proxy/src/test/certs/ocspsigner.p12 -->
                <cert>MIIDizCCAnOgAwIBAgIIOmOWEyqjUj0wDQYJKoZIhvcNAQEFBQAwNzERMA8GA1UE
                    AwwIQWRtaW5DQTExFTATBgNVBAoMDEVKQkNBIFNhbXBsZTELMAkGA1UEBhMCU0Uw
                    HhcNMTIwOTA2MTEzODMwWhcNMTQwOTA2MTEzODMwWjAWMRQwEgYDVQQDDAtPY3Nw
                    IFNpZ25lcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANZTdnxNq1QM
                    ncmiInNUSpm02V72GNrMrvq2Q4Zz3Zr8zDKMdAiwdrjx9X+Zi5oTjiSUXRuHY5ZN
                    9oeLO1cv9NV6OGk3MlrAzxquBfQUgnZMNLkPZW5SuLqlZpWf0vF7EvAVX20hxgMq
                    7M26Fxt/B9W81/G/REnuHKJ+nxCAZi5Kd1hdGVTEIwkicqROiEfQUcycs0T5aZI7
                    F5qFiZyo3AeRbWYyhEfe326cPaRaswo2WwcBjFYWibTCnNQuLgDL6qroL1T8soI6
                    LzBaNao6Lm4YY1OwTPz/UEiJ3KIXoAjfxMlOUnznmeWYNPcJb5Z8fdtWpaZqjV3W
                    IMAZocNThb8CAwEAAaOBuzCBuDBYBggrBgEFBQcBAQRMMEowSAYIKwYBBQUHMAGG
                    PGh0dHA6Ly9pa3MyLXVidW50dS5jeWJlci5lZTo4MDgwL2VqYmNhL3B1YmxpY3dl
                    Yi9zdGF0dXMvb2NzcDAdBgNVHQ4EFgQUI1mSgzcFjcBFmmjYwlc9Qm7yF/kwDAYD
                    VR0TAQH/BAIwADAfBgNVHSMEGDAWgBR3LYkuA7b9+NJlOTE1ItBGGujSCTAOBgNV
                    HQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQEFBQADggEBACRO2KTCVKQxYMlsMDkjT5Qj
                    zqW0wHNCsxieYv0qfDM1Z5ceW0c0KjJcKXESj7GXT7oNejwI4gZNgxIzemJ3xABH
                    dftk2WxLQBYJMKQ30EuisFKueqpxaLVkPAbt+XLxSrxaYePB9LTJ+rw3FtbiIbag
                    3AH22TFUUUnaTGVF+OiHtthE1u7bnwsTqWXX4PI9I3KnSaIEE55mveNq2jHVWu4r
                    Myy2flOZMonYh3dw1gmSp2yWo1YDpN3olM0Li6Lnfvg1TZd71xZ6ZkKf+MoAs+pW
                    2HaLh8hiYRXpgw3WVSBg6CPTLoU5xFb57BNL3qccVetmbpZgznHMYEBN4b4pyHk=
                </cert>
            </ocsp>
            <ocsp>
                <url>http://nihhuijaa.example.net/ocsp</url>
