=== AdapterKernel/X-Road/xtee6/common-util/src/main/resources/serverconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- TODO The file name: serverconf.xsd vs localconf.xsd vs proxyconf.xsd vs ... ??? -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sdsb.net/xsd/sdsb.xsd"
    targetNamespace="http://sdsb.net/xsd/sdsb.xsd" xmlns:id="http://sdsb.net/xsd/identifiers">

    <import namespace="http://sdsb.net/xsd/identifiers" schemaLocation="identifiers.xsd" id="id"/>
    <element name="serverConf" type="tns:ServerConfType"/>

    <complexType name="ServerConfType">
        <sequence>
            <element name="serverCode" type="string">
                <annotation>
                    <documentation>Code that identifies this security server.</documentation>
                </annotation>
            </element>
            <element name="owner" type="IDREF"/>
            <element name="client" type="tns:ClientType" minOccurs="0" maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        All organizations that are registered in this
                        security server.
                    </documentation>
                </annotation>
            </element>
            <element name="globalConfDistributor" type="tns:GlobalConfDistributorType" minOccurs="0"
                maxOccurs="unbounded">
                <annotation>
                    <documentation>
                        Information about the GlobalConf distributor.
                    </documentation>
                </annotation>
            </element>
            <element name="internalSSLCert" type="base64Binary" minOccurs="0">
                <annotation>
                    <documentation>Self-signed certificate used for internal ssl connections. The corresponding key is read from PKCS#12 file (file name is hardcoded).</documentation>
                </annotation>            
           </element>
            <element name="tsp" type="tns:TspType" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Time-stamp provider that is used by this security server.</documentation>
                </annotation>
            </element>
            <element name="asyncSender" minOccurs="0" type="tns:asyncSenderType">
                <annotation>
                    <documentation>Configuration parameters for async-sender.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="ClientType">
        <sequence>
            <element name="identifier" type="id:SdsbClientIdentifierType">
                <annotation>
                    <documentation>
                    </documentation>
                </annotation>
            </element>
            <element name="fullName" type="string" minOccurs="0">
                <annotation>
                    <documentation>The full, official name of the member, used in user interfaces.
                    </documentation>
                </annotation>
            </element>
            <element name="contacts" type="string" minOccurs="0">
                <annotation>
                    <documentation>Administrative contacts of the client, used in user interfaces.
                    </documentation>
                </annotation>
            </element>
            <element name="clientStatus" type="string" minOccurs="0">
                <annotation>
                    <documentation>Holds the current status of the client, used in user interface.
                    </documentation>
                </annotation>
            </element>
            <element name="wsdl" type="tns:WsdlType" maxOccurs="unbounded" minOccurs="0"/>
            <element name="localGroup" type="tns:LocalGroupType" maxOccurs="unbounded" minOccurs="0"/>
            <element name="isAuthentication" minOccurs="0">
                <annotation>
                    <documentation>If and how the connection with clients information systems is authenticated.</documentation>
                </annotation>
                <simpleType>
                    <restriction base="string">
                        <enumeration value="NOSSL"/>
                        <enumeration value="SSLNOAUTH"/>
                        <enumeration value="SSLAUTH"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="isCert" type="base64Binary" maxOccurs="unbounded" minOccurs="0">
                <annotation>
                    <documentation>Certificate that is used to communicate with internal information systems.</documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="id" type="ID"/>
    </complexType>

    <complexType name="ServiceType">
        <sequence>
            <element name="serviceCode" type="string">
                <annotation>
                    <documentation>Operation name in WSDL.</documentation>
                </annotation>
            </element>
            <element name="serviceVersion" type="string" minOccurs="0">
                <annotation>
                    <documentation>Operation version in WSDL.</documentation>
                </annotation>
            </element>
            <element name="title" type="string" minOccurs="0">
                <annotation>
                    <documentation>Title in WSDL.</documentation>
                </annotation>
            </element>
            <!-- URL on optional, kuna konfi redigeerimisel voib kasutaja seda mitte sisestada. -->
            <element name="url" type="anyURI" minOccurs="0">
                <annotation>
                    <documentation>The URL of the service.</documentation>
                </annotation>
            </element>
            <element name="timeout" type="int">
                <annotation>
                    <documentation>Timeout for the service, in seconds.</documentation>
                </annotation>
            </element>
            <element name="requiredSecurityCategory" maxOccurs="unbounded" minOccurs="0"
                type="id:SdsbSecurityCategoryIdentifierType"/>
            <element maxOccurs="unbounded" minOccurs="0" name="authorizedSubject"
                type="tns:AuthorizedSubjectType">
                <annotation>
                    <documentation>Identifier of the subject (SDSB member, subsystem, global group or local group) who is authorized to access this service.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="AuthorizedSubjectType">
        <annotation>
            <documentation>
                Subject (SDSB member, subsystem, global group or local group) who is authorized to access a service.
            </documentation>
        </annotation>
        <sequence>
            <element name="subjectId" type="id:SdsbIdentifierType">
                <annotation>
                    <documentation>Identifier of the subject (SDSB member, subsystem, global group or local group) who is authorized to access a service.</documentation>
                </annotation>
            </element>
            <element name="rightsGiven" type="dateTime">
                <annotation>
                    <documentation>Date and time when access rights to a service were given to this subject.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="TspType">
        <sequence>
            <element name="name" type="string" minOccurs="0">
                <annotation>
                    <documentation>Name for the time-stamp provider as it is given in global configuration.</documentation>
                </annotation>
            </element>
            <element name="url" type="anyURI" minOccurs="0">
                <annotation>
                    <documentation>URL for the time-stamp provider.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="GlobalConfDistributorType">
        <annotation>
            <documentation>
                A GlobalConf distributor.
            </documentation>
        </annotation>
        <sequence>
            <element name="url" type="string">
                <annotation>
                    <documentation>The URL of the distributor.</documentation>
                </annotation>
            </element>
            <element name="verificationCert" type="base64Binary">
                <annotation>
                    <documentation>Certificate used to verify the signed GlobalConf.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>

    <complexType name="asyncSenderType">
        <sequence>
            <element name="baseDelay" type="int" default="300">
                <annotation>
                    <documentation>Delay between the first and second sending attempt, in seconds</documentation>
                </annotation>
            </element>
            <element name="maxDelay" type="int" default="1800">
                <annotation>
                    <documentation>Maximum delay between sending attempts, in seconds</documentation>
                </annotation>
            </element>
            <element name="maxSenders" type="int" default="1000">
                <annotation>
                    <documentation>Number of parallel sends</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="LocalGroupType">
        <sequence>
            <element name="groupCode" type="string"/>
            <element name="description" type="string"/>
            <element name="groupMember" maxOccurs="unbounded" minOccurs="0"
                type="tns:GroupMemberType"/>
            <element name="updated" type="dateTime"/>
        </sequence>
    </complexType>

    <complexType name="GroupMemberType">
        <annotation>
            <documentation>
                SDSB Member or a subsystem who is part of a local group.
            </documentation>
        </annotation>
        <sequence>
            <element name="groupMemberId" type="id:SdsbClientIdentifierType"/>
            <element name="added" type="dateTime">
                <annotation>
                    <documentation>Date and time of adding the member to the group.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
    
    <complexType name="WsdlType">
        <sequence>
            <element name="url" type="anyURI"/>
            <element name="wsdlLocation" type="string" minOccurs="0">
                <annotation>
                    <documentation>Location of the cached WSDL file in the file system.</documentation>
                </annotation>
            </element>
            <element name="disabled" type="boolean">
                <annotation>
                    <documentation>If true, then queries to services under this WSDL will result in error message.</documentation>
                </annotation>
            </element>
            <element name="disabledNotice" type="string" minOccurs="0">
                <annotation>
                    <documentation>Notice to queries if this WSDL is disabled.</documentation>
                </annotation>
            </element>
            <element name="publish" type="boolean"/>
            <element minOccurs="0" name="publishedDate" type="dateTime"/>
            <element name="refreshedDate" type="dateTime"/>
            <element maxOccurs="unbounded" minOccurs="0" name="service" type="tns:ServiceType"/>
            <element name="backend" type="string" minOccurs="0">
                <annotation>
                    <documentation>Specifies the backend type. By default it is assumed that backend is SDSB.</documentation>
                </annotation>
            </element>
            <element name="backendURL" type="anyURI" minOccurs="0">
                <annotation>
                    <documentation>Specifies the backend address.</documentation>
                </annotation>
            </element>
        </sequence>
    </complexType>
</schema>

=== AdapterKernel/X-Road/xtee6/async-sender/src/test/resources/serverconf.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:serverConf xmlns:ns2="http://sdsb.net/xsd/identifiers"
    xmlns:ns3="http://sdsb.net/xsd/sdsb.xsd"
    ns3:schemaLocation="http://sdsb.net/xsd/sdsb.xsd ../../../common-util/src/main/resources/serverconf.xsd">
    <serverCode>ProducerServerConf</serverCode>
    <owner>owner</owner>

    <client id="owner">
        <identifier ns2:objectType="MEMBER">
            <ns2:sdsbInstance>EE</ns2:sdsbInstance>
            <ns2:memberClass>BUSINESS</ns2:memberClass>
            <ns2:memberCode>producer</ns2:memberCode>
        </identifier>
        <fullName>Experimental producer</fullName>
        <wsdl>
            <!-- TODO -->
            <url>http://consumer.com</url>
            <wsdlLocation>kusagil/elvas</wsdlLocation>
            <disabled>false</disabled>
            <publish>true</publish>
            <publishedDate>2011-12-31T12:00:00</publishedDate>
            <refreshedDate>2012-12-31T14:00:00</refreshedDate>

            <service>
                <serviceCode>bodyMassIndex</serviceCode>
                <url>http://127.0.0.1:8081/bodyMassIndex</url>
                <timeout>20</timeout>
                <requiredSecurityCategory
                    ns2:objectType="MEMBER">
                    <ns2:sdsbInstance>EE</ns2:sdsbInstance>
                    <ns2:securityCategoryCode>XXX
                    </ns2:securityCategoryCode>
                </requiredSecurityCategory>
                <authorizedSubject>
                    <subjectId
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="ns2:SdsbClientIdentifierType"
                        ns2:objectType="MEMBER">
                        <ns2:sdsbInstance>EE</ns2:sdsbInstance>
                        <ns2:memberClass>BUSINESS</ns2:memberClass>
                        <ns2:memberCode>clientmember</ns2:memberCode>
                    </subjectId>
                    <rightsGiven>2013-09-05T15:07:45.386+03:00
                    </rightsGiven>
                </authorizedSubject>
            </service>

            <service>
                <serviceCode>bigSoap</serviceCode>
                <timeout>30</timeout>
            </service>

            <service>
                <serviceCode>bigAttachment</serviceCode>
                <timeout>30</timeout>
            </service>

            <service>
                <serviceCode>examReport</serviceCode>
                <url>http://127.0.0.1:8081/examReport</url>
                <timeout>30</timeout>
            </service>

            <service>
                <serviceCode>getState</serviceCode>
                <url>http://127.0.0.1:8081/getState</url>
                <timeout>30</timeout>

                <authorizedSubject>
                    <subjectId
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:type="ns2:SdsbClientIdentifierType"
                        ns2:objectType="MEMBER">
                        <ns2:sdsbInstance>EE</ns2:sdsbInstance>
                        <ns2:memberClass>BUSINESS</ns2:memberClass>
                        <ns2:memberCode>consumer</ns2:memberCode>
                    </subjectId>
                    <rightsGiven>2013-09-05T15:07:45.386+03:00
                    </rightsGiven>
                </authorizedSubject>

            </service>

            <service>
                <serviceCode>smallAttachment</serviceCode>
                <timeout>30</timeout>
            </service>

            <service>
                <serviceCode>testQuery</serviceCode>
                <timeout>30</timeout>
            </service>

            <service>
                <serviceCode>async</serviceCode>
                <url>http://127.0.0.1:8081/async</url>
                <timeout>30</timeout>
            </service>
        </wsdl>
    </client>


    <!--identifier>foobar</identifier> <member> <identifier>producer</identifier> 
        <fullName>Experimental producer</fullName> <service> <name>testQuery</name> 
        <url>http://127.0.0.1:8081/testQuery</url> <acl> <client>consumer</client> 
        </acl> </service> <service> <name>getState</name> <url>http://127.0.0.1:8081/getState</url> 
        <acl> <client>consumer</client> </acl> </service> <service> <name>bigSoap</name> 
        <url>http://127.0.0.1:8081/bigSoap</url> <acl> <client>consumer</client> 
        </acl> </service> <service> <name>smallAttachment</name> <url>http://127.0.0.1:8081/smallAttachment</url> 
        <acl> <client>consumer</client> </acl> </service> <service> <name>bigAttachment</name> 
        <url>http://127.0.0.1:8081/bigAttachment</url> <acl> <client>consumer</client> 
        </acl> </service> <service> <name>bodyMassIndex</name> <url>http://127.0.0.1:8081/bodyMassIndex</url> 
        <acl> <client>consumer</client> </acl> </service> <service> <name>examReport</name> 
        <url>http://127.0.0.1:8081/examReport</url> <acl> <client>consumer</client> 
        </acl> </service> </member> <member> <identifier>consumer</identifier> <fullName>Experimental 
        consumer</fullName> </member -->

    <globalConfDistributor>
        <!--<url>http://iks2-central.cyber.ee/globalconf</url> -->
        <url>file:../systemtest/conf/local_test/globalconf.xml.signed
        </url>
        <verificationCert>
            MIICPTCCAaYCCQDhAMDISeX12TANBgkqhkiG9w0BAQUFADBjMQswCQYDVQQGEwJF
            RTERMA8GA1UECAwIVGFydHVtYWExDjAMBgNVBAcMBVRhcnR1MRQwEgYDVQQKDAtD
            eWJlcm5ldGljYTEMMAoGA1UECwwDSVRPMQ0wCwYDVQQDDAREZW1vMB4XDTEzMDIw
            NTA4MjIzOFoXDTIzMDIwMzA4MjIzOFowYzELMAkGA1UEBhMCRUUxETAPBgNVBAgM
            CFRhcnR1bWFhMQ4wDAYDVQQHDAVUYXJ0dTEUMBIGA1UECgwLQ3liZXJuZXRpY2Ex
            DDAKBgNVBAsMA0lUTzENMAsGA1UEAwwERGVtbzCBnzANBgkqhkiG9w0BAQEFAAOB
            jQAwgYkCgYEAxe1NWPzMunQZrYa+q7oblnrfmbEeip21BetODfa1bNbEukaPMHWe
            hgrF1o5qNbMGNHyBNnU9M2nACx2jtps6SdeZSrfa7wgKlaf7ewnEjq2m3h3s4S1l
            NsVsCqsgGaPLQ7e0v0EL5UidsA18zic8etcHsU8T+Tjzw6EnAyaqoxsCAwEAATAN
            BgkqhkiG9w0BAQUFAAOBgQB5VCoeaHsWCrSW8UbPWAuUXaiKZb7tZLRanD1P5aGT
            Ps8WuY8Ob0qyAM1o7W09fjjJmpiqOP/HrhjwGQI63KQLYJH3xEeZNKkTrVdy6uqa
            hUuz1B/jn5ebqN3ZN/e9jUCfXJHxxWwx+K6FydQcAlRdXGnT7y2BEAOqlclQFOWY
            eA==
        </verificationCert>
    </globalConfDistributor>

    <asyncSender>
        <baseDelay>333</baseDelay>
        <maxDelay>666</maxDelay>
        <maxSenders>999</maxSenders>
    </asyncSender>
</ns3:serverConf>
